version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/:/etc/grafana/provisioning/
  tempo:
    image: grafana/tempo:2.2.3
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo_data:/tmp/tempo
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4318:4318"
      - "4317:4317"
  extsvc:
    image: ghcr.io/bamorim/postion-extsvc:latest
    volumes:
      - ./extsvc/jwt.crt:/home/ballerina/jwt.crt
      - ./extsvc/jwt.key:/home/ballerina/jwt.key
      - ./extsvc/DockerConfig.toml:/home/ballerina/Config.toml
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.6.0
    volumes:
      - ./docker/toxiproxy/toxiproxy.json:/toxiproxy.json
    command: [ "-config=/toxiproxy.json", "-host=0.0.0.0" ]
    ports:
      - "8474:8474"
      - "8080:8080"
      - "5432:5432"
  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  prometheus_data: {}
  postgres_data: {}
  grafana_data: {}
  tempo_data: {}