version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  grafana:
    image: grafana/grafana:10.1.5
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/:/etc/grafana/provisioning/
  tempo:
    image: grafana/tempo:2.2.3
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo_data:/tmp/tempo
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "4318:4318"
      - "4317:4317"
  extsvc:
    image: extsvc:latest
    build: ./extsvc/target/docker
    volumes:
      - ./extsvc/jwt.crt:/home/ballerina/jwt.crt
      - ./extsvc/jwt.key:/home/ballerina/jwt.key
      - ./extsvc/ExampleConfig.toml:/home/ballerina/Config.toml
    ports:
      - "8080:8080"
volumes:
  postgres_data: {}
  grafana_data: {}
  tempo_data: {}