[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="localhost"
agentPort=4317

[ballerina.http.accessLogConfig]
# Enable printing access logs on the Console. The default value is `false`.
console = true